import Link from 'next/link';
import MarketingNav from '@/components/MarketingNav';
import MarketingFooter from '@/components/MarketingFooter';

const GROUPS = [
  {
    title: 'Product and setup',
    questions: [
      ['What does Luxus Bot do?', 'Luxus Bot connects a WhatsApp support workflow with your business knowledge and team. The assistant can answer common questions, while your team can review conversations and take over when a person is needed.'],
      ['Do customers need to install anything?', 'No. Customers continue messaging your business on WhatsApp as usual.'],
      ['How does the assistant learn about my business?', 'Add your FAQs, product information, prices, and policies to the workspace knowledge base. Keep that information current so replies reflect your business.'],
      ['Can a teammate take over a conversation?', 'Yes. Your team can review conversations and handle requests that need a person, without asking the customer to move to another app.'],
      ['How do I connect WhatsApp?', 'The setup flow guides you through connecting your WhatsApp account. You can check connection status in the dashboard.'],
    ],
  },
  {
    title: 'Plans and billing',
    questions: [
      ['Is there a free trial?', 'There is no free trial. Choose a plan and complete payment; your account is created after payment succeeds. Renew manually from Billing each month to keep your subscription active.'],
      ['What counts as an AI reply?', 'An AI reply is a response generated by the assistant to a customer message. Replies written by your team do not count toward the AI reply allowance.'],
      ['What happens when I reach my reply limit?', 'When the monthly allowance is used, new conversations can be passed to your team until the next billing period.'],
      ['How are payments handled?', 'Payments are processed through Kora. Prices are displayed in US dollars and converted to the currency configured for your Kora account at checkout. Renewals are manual.'],
      ['Can I change plans?', 'Plan changes are managed from the Billing area of your workspace. Review the available plans and their included usage before switching.'],
    ],
  },
  {
    title: 'Data and AI',
    questions: [
      ['Is my business data shared with other businesses?', 'No. Each business has its own conversations, knowledge base, and settings, isolated from other businesses on the platform.'],
      ['Do I need my own Anthropic API key?', 'No. Luxus Bot can work without you supplying a key. If you want to manage AI billing with your own Anthropic key, you can add it in Settings.'],
      ['What if the assistant cannot answer?', 'Your team can take over when a question needs context or judgment. You can also improve the knowledge base with the information that was missing.'],
      ['Where can I read the privacy details?', 'See the Privacy page for the current summary of data handling. It is marked as a draft template and should be reviewed for your jurisdiction before being relied on.'],
    ],
  },
];

export const metadata = {
  title: 'FAQ | Luxus Bot',
  description: 'Answers about Luxus Bot setup, WhatsApp support, plans, billing, and data.',
};

export default function FAQPage() {
  return (
    <div className="min-h-screen bg-[#f7f7f2]">
      <MarketingNav />

      <section className="border-b border-stone-200 bg-white">
        <div className="mx-auto grid max-w-7xl gap-6 px-5 py-14 sm:px-8 sm:py-20 lg:grid-cols-[1fr_0.7fr] lg:items-end lg:gap-16 lg:px-10">
          <div>
            <p className="text-xs font-semibold text-[#285b43]">HELP CENTER</p>
            <h1 className="mt-3 font-display text-4xl leading-tight text-ink-900 sm:text-5xl">Answers before you get started.</h1>
          </div>
          <p className="max-w-xl text-base leading-7 text-ink-600">Browse setup, billing, and data questions. If you need a hand with something specific, our contact page has the right inbox.</p>
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-8 sm:py-16 lg:grid-cols-[220px_1fr] lg:gap-16 lg:px-10">
        <nav aria-label="FAQ sections" className="flex gap-2 overflow-x-auto lg:sticky lg:top-6 lg:block lg:self-start">
          {GROUPS.map(({ title }, index) => (
            <a key={title} href={`#faq-${index + 1}`} className="shrink-0 rounded-md border border-stone-200 bg-white px-3 py-2 text-xs font-medium text-ink-700 hover:border-[#9bc5a6] lg:mb-2 lg:block lg:px-4 lg:py-3 lg:text-sm">
              {title}
            </a>
          ))}
        </nav>

        <div className="space-y-12">
          {GROUPS.map(({ title, questions }, groupIndex) => (
            <section key={title} id={`faq-${groupIndex + 1}`} className="scroll-mt-8">
              <h2 className="font-display text-2xl text-ink-900">{title}</h2>
              <div className="mt-4 divide-y divide-stone-200 border-y border-stone-200">
                {questions.map(([question, answer]) => (
                  <details key={question} className="group py-4">
                    <summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm font-semibold text-ink-900 marker:hidden">
                      {question}
                      <span aria-hidden="true" className="font-normal text-[#285b43] transition group-open:rotate-45">+</span>
                    </summary>
                    <p className="max-w-3xl pr-8 pt-3 text-sm leading-6 text-ink-600">{answer}</p>
                  </details>
                ))}
              </div>
            </section>
          ))}
        </div>
      </section>

      <section className="border-t border-stone-200 bg-white">
        <div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-10">
          <div>
            <h2 className="font-display text-2xl text-ink-900">Need an answer for your setup?</h2>
            <p className="mt-2 text-sm text-ink-600">Send us the details and we&apos;ll point you in the right direction.</p>
          </div>
          <Link href="/contact" className="inline-flex min-h-11 items-center justify-center rounded-md bg-[#285b43] px-5 text-sm font-semibold text-white hover:bg-[#204a36]">Contact Luxus Bot</Link>
        </div>
      </section>

      <MarketingFooter />
    </div>
  );
}