import logger from '../../utils/logger.js';
import config from '../../config/index.js';
import AnthropicProvider from './providers/anthropic.js';
import PromptBuilder from './promptBuilder.js';
import { isBusinessHours, formatBusinessHours, formatNextBusinessOpening } from '../../utils/helpers.js';

/**
 * AIEngine - Anthropic (Claude) only.
 * Every reply is generated by the Anthropic provider; there is no provider switching.
 */
class AIEngine {
  /**
   * @param {object} [options]
   * @param {import('../tenant/TenantContext.js').default} [options.tenantContext] -
   *   when provided, providers are built from THIS tenant's decrypted keys and
   *   the prompt uses this tenant's company/assistant/business-hours info.
   *   Omitted only for the legacy single-tenant client, which falls back to
   *   the platform-level config (same behavior as before tenant threading).
   * @param {object} [options.knowledgeBase] - tenant-scoped KnowledgeBase instance
   */
  constructor(options = {}) {
    const { tenantContext = null, knowledgeBase = null } = options;
    this.tenantContext = tenantContext;

    const aiConfig = tenantContext ? tenantContext.getAIConfig() : null;

    this.providers = {
      anthropic: new AnthropicProvider(aiConfig ? { apiKey: aiConfig.anthropicKey, temperature: aiConfig.temperature, maxTokens: aiConfig.maxTokens } : {}),
    };

    this.defaultProvider = 'anthropic';
    this.knowledgeBase = knowledgeBase;
    this.promptBuilder = new PromptBuilder();
    
    // Kept for the health endpoint; a single provider means nothing to rotate
    this.currentProviderIndex = 0;
    this.availableProviders = [];
    this.lastBalanceCheck = 0;

    this.providerHealth = {
      anthropic: { available: true, failures: 0, lastCheck: Date.now(), usage: 0 },
    };
  }

  /**
   * Generate response using load balancer
   */
  async generateResponse(params) {
    const { message, context, history, module, user } = params;

    try {
      // Build messages for AI
      const companyInfo = this.tenantContext ? this.tenantContext.companyInfo : config.company;
      const assistantInfo = this.tenantContext
        ? this.tenantContext.assistantInfo
        : { name: config.assistant.name, personality: config.assistant.personality };
      const businessHours = this.tenantContext ? this.tenantContext.businessHours : config.businessHours;

      const messages = await this.promptBuilder.buildMessages({
        message,
        context,
        history,
        module,
        user,
        companyInfo,
        assistantInfo,
        businessHours,
      });

      // Enhance with knowledge base
      if (this.knowledgeBase && message) {
        const relevantKnowledge = await this.knowledgeBase.search(message, 3);
        if (relevantKnowledge && relevantKnowledge.length > 0) {
          messages.push({
            role: 'system',
            content: `Relevant knowledge:\n${relevantKnowledge.map(k => k.content).join('\n\n')}`,
          });
        }
      }

      const provider = await this.selectProvider();
      if (!provider) {
        logger.error('Anthropic is not configured (missing ANTHROPIC_API_KEY)');
        return this.getFallbackResponse(context);
      }

      let result;
      try {
        result = await this.generateWithRetry(provider, messages, 2);
        logger.info(`✅ Response generated with ${provider.getName()}`);
      } catch (error) {
        logger.error(`❌ ${provider.getName()} failed: ${error.message}`);
        return this.getFallbackResponse(context);
      }

      // Process and track
      const enhancedResponse = this.processResponse(result, context, businessHours);
      this.trackUsage(result);

      return enhancedResponse;
    } catch (error) {
      logger.error('Error generating AI response:', error);
      return this.getFallbackResponse(context);
    }
  }

  /**
   * Returns the Anthropic provider, or null when no API key is configured.
   * There is nothing to fall back to, so a past failure never disables it:
   * the next message simply tries again.
   */
  async selectProvider() {
    const provider = this.providers.anthropic;
    if (!provider || !provider.client) return null;
    this.availableProviders = ['anthropic'];
    this.providerHealth.anthropic.usage++;
    return provider;
  }

  /**
   * Generate with retry logic
   */
  async generateWithRetry(provider, messages, maxRetries = 2) {
    let lastError;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const result = await provider.generateCompletion(messages);
        
        // Mark provider as healthy
        this.providerHealth[provider.getName()].available = true;
        this.providerHealth[provider.getName()].failures = 0;
        
        return result;
      } catch (error) {
        lastError = error;
        logger.warn(`AI generation attempt ${attempt} failed:`, error.message);
        
        this.providerHealth[provider.getName()].failures++;
        
        if (attempt < maxRetries) {
          await new Promise(resolve => setTimeout(resolve, 1000 * attempt));
        }
      }
    }

    // All retries failed (health is informational only; the next message tries again)
    this.providerHealth[provider.getName()].lastCheck = Date.now();

    throw lastError;
  }

  /**
   * Check if a provider is actually available
   */
  async checkProviderAvailability(provider) {
    try {
      const available = await Promise.race([
        provider.isAvailable(),
        new Promise((_, reject) => 
          setTimeout(() => reject(new Error('Timeout')), 3000)
        )
      ]);
      return available;
    } catch (error) {
      logger.debug(`Provider availability check failed: ${error.message}`);
      return false;
    }
  }

  /**
   * Process and enhance AI response
   */
  processResponse(result, context, businessHours = this.tenantContext ? this.tenantContext.businessHours : config.businessHours) {
    const response = {
      text: result.text,
      provider: result.provider,
      model: result.model,
      usage: result.usage,
      cost: result.cost,
      duration: result.duration,
      actions: [],
    };

    // Check for out of hours
    if (!isBusinessHours(businessHours)) {
      const nextOpening = formatNextBusinessOpening(businessHours);
      const customNotice = businessHours.outOfHoursMessage?.trim();
      const notice = customNotice
        ? [customNotice, nextOpening].filter(Boolean).join('\n\n')
        : nextOpening || `_Note: We're currently outside business hours. Our team will follow up during business hours (${formatBusinessHours(businessHours)})._`;
      response.text += `\n\n${notice}`;
    }

    // Extract actions from response
    response.actions = this.extractActions(result.text);

    // Handle function calls
    if (result.functionCall) {
      response.functionCall = result.functionCall;
      response.actions.push({
        type: 'function_call',
        name: result.functionCall.name,
        arguments: result.functionCall.arguments,
      });
    }

    return response;
  }

  /**
   * Extract actions from AI response
   */
  extractActions(text) {
    const actions = [];

    if (text.includes('?') && text.split('?').length > 2) {
      actions.push({
        type: 'expecting_response',
        category: 'question',
      });
    }

    if (text.toLowerCase().includes('create a ticket') || 
        text.toLowerCase().includes('escalate')) {
      actions.push({
        type: 'create_ticket',
        priority: 'normal',
      });
    }

    return actions;
  }

  /**
   * Get fallback response
   */
  getFallbackResponse(context) {
    const companyEmail = this.tenantContext ? this.tenantContext.companyInfo.email : config.company.email;
    const fallbackMessages = [
      "I apologize, but I'm experiencing technical difficulties. Please try again in a moment.",
      "I'm having trouble processing your request right now. Please try again shortly.",
      "I'm temporarily unavailable. Please contact us directly if this is urgent.",
    ];

    const randomIndex = Math.floor(Math.random() * fallbackMessages.length);
    const message = fallbackMessages[randomIndex];

    if (companyEmail) {
      return {
        text: `${message}\n\nFor immediate assistance, please email us at ${companyEmail}`,
        provider: 'fallback',
        actions: [],
      };
    }

    return {
      text: message,
      provider: 'fallback',
      actions: [],
    };
  }

  /**
   * Track usage for analytics
   */
  trackUsage(result) {
    logger.info('AI usage', {
      provider: result.provider,
      model: result.model,
      tokens: result.usage?.totalTokens ?? 0,
      cost: result.cost ?? 0,
      duration: result.duration,
    });
  }

  /**
   * Generate embeddings
   */
  async generateEmbeddings() {
    // Anthropic has no embeddings API. Callers (vector store) catch this and
    // knowledge search falls back to the database text search.
    throw new Error('Embeddings are not available with Anthropic; using text search instead');
  }

  /**
   * Analyze sentiment
   */
  async analyzeSentiment(text) {
    try {
      const messages = [
        {
          role: 'system',
          content: 'Analyze the sentiment of the following text. Respond with only one word: very_negative, negative, neutral, positive, or very_positive.',
        },
        {
          role: 'user',
          content: text,
        },
      ];

      const provider = await this.selectProvider();
      const result = await provider.generateCompletion(messages, {
        maxTokens: 10,
        temperature: 0,
      });

      const sentiment = result.text.trim().toLowerCase();
      const validSentiments = ['very_negative', 'negative', 'neutral', 'positive', 'very_positive'];

      return validSentiments.includes(sentiment) ? sentiment : 'neutral';
    } catch (error) {
      logger.error('Error analyzing sentiment:', error);
      return 'neutral';
    }
  }

  /**
   * Detect language
   */
  async detectLanguage(text) {
    try {
      const messages = [
        {
          role: 'system',
          content: 'Detect the language of the following text. Respond with only the ISO 639-1 language code (e.g., en, es, fr).',
        },
        {
          role: 'user',
          content: text,
        },
      ];

      const provider = await this.selectProvider();
      const result = await provider.generateCompletion(messages, {
        maxTokens: 10,
        temperature: 0,
      });

      return result.text.trim().toLowerCase();
    } catch (error) {
      logger.error('Error detecting language:', error);
      return 'en';
    }
  }

  /**
   * Get provider health status with load balancing stats
   */
  getProviderHealth() {
    const health = {};
    
    for (const [name, status] of Object.entries(this.providerHealth)) {
      const provider = this.providers[name];
      health[name] = {
        ...status,
        enabled: this.isProviderEnabled(name),
        model: provider?.getModel?.() || 'unknown',
        inRotation: this.availableProviders.includes(name),
      };
    }
    
    return {
      providers: health,
      loadBalancing: {
        mode: this.defaultProvider,
        availableProviders: this.availableProviders,
        currentIndex: this.currentProviderIndex,
        nextProvider: this.availableProviders[this.currentProviderIndex] || null,
      },
    };
  }

  /**
   * Check if provider is enabled
   */
  isProviderEnabled(providerName) {
    return providerName === 'anthropic' && Boolean(this.providers.anthropic?.client);
  }

  /**
   * Reset provider health
   */
  resetProviderHealth(providerName) {
    if (this.providerHealth[providerName]) {
      this.providerHealth[providerName].available = true;
      this.providerHealth[providerName].failures = 0;
      this.providerHealth[providerName].lastCheck = Date.now();
      logger.info(`Reset health for provider: ${providerName}`);
    }
  }

  /**
   * Reset all providers health
   */
  resetAllProvidersHealth() {
    for (const providerName of Object.keys(this.providerHealth)) {
      this.resetProviderHealth(providerName);
    }
    this.lastBalanceCheck = 0; // Force refresh on next request
    logger.info('Reset health for all providers');
  }

  /**
   * Set knowledge base
   */
  setKnowledgeBase(knowledgeBase) {
    this.knowledgeBase = knowledgeBase;
  }
}

export default AIEngine;
